Update bot.yml

diff --git a/.github/workflows/bot.yml b/.github/workflows/bot.yml
--- a/.github/workflows/bot.yml
+++ b/.github/workflows/bot.yml
@@ -17,12 +17,12 @@ jobs:
   benchmark:
     name: Macro Benchmarks
     if: contains(github.event.pull_request.labels.*.name, 'ci:benchmark')
-    runs-on: ubuntu-latest
+    runs-on: benchmarking-runner
     permissions:
       pull-requests: write
       contents: write
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
 
       - name: Install Stable Toolchain
         uses: actions-rs/toolchain@v1
@@ -31,105 +31,129 @@ jobs:
           override: true
           components: rustfmt, clippy
 
-      - name: Run Benchmarks and Build Time Checks
-        if: contains(github.event.pull_request.labels.*.name, 'ci:benchmark')
-        runs-on: ubuntu-latest
-        permissions:
-          pull-requests: write
-          contents: write
-        steps:
-          - name: Checkout code
-            uses: actions/checkout@v2
+     
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-          - name: Install Stable Toolchain
-            uses: actions-rs/toolchain@v1
-            with:
-              toolchain: stable
-              override: true
-              components: rustfmt, clippy
+      - name: Install Stable Toolchain
+        uses: actions-rs/toolchain@v1
+        with:
+          toolchain: stable
+          override: true
+          components: rustfmt, clippy
 
-          - name: Cache Rust Dependencies
-            uses: actions/cache@v3
-            with:
-              path: |
-                ~/.cargo/registry
-                ~/.cargo/git
-                target
-              key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
+      - name: Cache Rust Dependencies
+        uses: actions/cache@v3
+        with:
+          path: |
+            ~/.cargo/registry
+            ~/.cargo/git
+            target
+          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
 
-          - name: Run Cargo Build
-            uses: actions-rs/cargo@v1
-            with:
-              command: build
-              args: --release
+      - name: Run Cargo Build
+        uses: actions-rs/cargo@v1
+        with:
+          command: build
+          args: --release
 
-          - name: Run Benchmark Tests
-            run: |
-              cargo bench
+       - name: Run Benchmark Tests
+        run: |
+          cargo bench
 
-          - name: Install Nginx
-            run: |
-              sudo apt-get update
-              sudo apt-get install -y nginx
+      - name: Calculate Build Time Change
+        id: build_time
+        run: |
+          # Add a script to calculate the build time change and store it as an output variable.
+          # For example, you can use the following script:
+          BUILD_TIME_PERCENT_CHANGE=$(./calculate_build_time_change.sh)
+          echo "Build time change: $BUILD_TIME_PERCENT_CHANGE%"
+          echo "::set-output name=build_time_change::$BUILD_TIME_PERCENT_CHANGE"
 
-          - name: Clean Up
-            run: |
-              sudo rm -rf /etc/nginx/sites-enabled/default
+      - name: Publish Benchmark Report
+        run: |
+          # Add a script to generate and publish the benchmark report.
 
-          - name: Copy Nginx Configuration
-            working-directory: ci-benchmark
-            run: |
-              sudo cp nginx.conf /etc/nginx/
+      - name: Post Comment on PR
+        if: always()
+        run: |
+          # Post a comment on the PR with benchmark and build time information.
 
-          - name: Test Nginx Configuration
-            run: |
-              sudo nginx -t
+      - name: Set Status Check
+        if: always()
+        run: |
+          # Set the status check to success or failure based on the benchmark and build time results.
 
-          - name: Start Nginx
-            run: |
-              sudo systemctl start nginx
+      - name: Fail CI on Benchmark Degradation
+        if: steps.build_time.outputs.build_time_change > 10
+        run: exit 1
+      - name: Run Tailcall
+        run: |
+          ./target/release/tailcall start ci-benchmark/benchmark.graphql&
 
-          - name: Install Wrk
-            run: |
-              sudo apt-get install -y wrk
+      - name: Install Nginx
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y nginx
 
-          - name: Run Test Query
-            run: |
-              curl -i -X POST -d '{"query": "{posts{title}}"}' http://localhost:8000/graphql -H "Content-Type: application/json"
+      - name: Clean Up
+        run: |
+          sudo rm -rf /etc/nginx/sites-enabled/default
 
-          - id: run_wrk
-            name: Run Wrk
-            working-directory: ci-benchmark
-            run: |
-              wrk -d 30 -t 1 -c 100 -s wrk.lua http://localhost:8000/graphql > wrk-output.txt
+      - name: Copy Nginx Configuration
+        working-directory: ci-benchmark
+        run: |
+          sudo cp nginx.conf /etc/nginx/
 
-          - id: convert_wrk_output_markdown
-            name: Convert Output to Markdown
-            working-directory: ci-benchmark
-            run: |
-              node wrk-output-to-md.js wrk-output.txt > wrk-output.md
+      - name: Test Nginx Configuration
+        run: |
+          sudo nginx -t
 
-          - id: cat_md
-            name: Cat Markdown
-            working-directory: ci-benchmark
-            run: |
-              cat wrk-output.md
+      - name: Start Nginx
+        run: |
+          sudo systemctl start nginx
 
-          - id: get_comment_body
-            name: Get Comment Body
-            working-directory: ci-benchmark
-            run: |
-              body="$(cat wrk-output.md)"
-              delimiter="$(openssl rand -hex 8)"
-              echo "body<<$delimiter" >> $GITHUB_OUTPUT
-              echo "$body" >> $GITHUB_OUTPUT
-              echo "$delimiter" >> $GITHUB_OUTPUT
+      - name: Install Wrk
+        run: |
+          sudo apt-get install -y wrk
 
-          - name: Create Commit Comment
-            uses: peter-evans/commit-comment@v3
-            with:
-              sha: ${{github.event.pull_request.head.sha}}
-              body: ${{steps.get_comment_body.outputs.body}}
+      - name: Run Test Query
+        run: |
+          curl -i -X POST -d '{"query": "{posts{title}}"}' http://localhost:8000/graphql -H "Content-Type: application/json"
+
+      - id: run_wrk
+        name: Run Wrk
+        working-directory: ci-benchmark
+        run: |
+          wrk -d 30 -t 1 -c 100 -s wrk.lua http://localhost:8000/graphql > wrk-output.txt
+
+      - id: convert_wrk_output_markdown
+        name: Convert Output to Markdown
+        working-directory: ci-benchmark
+        run: |
+          node wrk-output-to-md.js wrk-output.txt > wrk-output.md
+
+      - id: cat_md
+        name: Cat Markdown
+        working-directory: ci-benchmark
+        run: |
+          cat wrk-output.md
+
+      - id: get_comment_body
+        name: Get Comment Body
+        working-directory: ci-benchmark
+        run: |
+          body="$(cat wrk-output.md)"
+          delimiter="$(openssl rand -hex 8)"
+          echo "body<<$delimiter" >> $GITHUB_OUTPUT
+          echo "$body" >> $GITHUB_OUTPUT
+          echo "$delimiter" >> $GITHUB_OUTPUT
+
+      - name: Create Commit Comment
+        uses: peter-evans/commit-comment@v3
+        with:
+          sha: ${{github.event.pull_request.head.sha}}
+          body: ${{steps.get_comment_body.outputs.body}}
 
   lint:
     name: CI:Lint
@@ -143,16 +167,13 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: "18"
-
       - name: Install Prettier
         run: npm install --global prettier
-
       - name: Install Stable Toolchain
         uses: actions-rs/toolchain@v1
         with:
           toolchain: nightly
           components: rustfmt, clippy
-
       - name: Cache Rust Dependencies
         uses: actions/cache@v3
         with:
@@ -161,9 +182,7 @@ jobs:
             ~/.cargo/git
             target
           key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
-
       - uses: actions/checkout@v4
-
       - name: Run lint script
         run: ./lint.sh --mode=fix
       - name: Commit and push if changed
